title: Yung Chu Chiang
logo: /assets/img/profile_circle.png
description: Hi, I'm Yung-Chu. Future web developer creating user-friendly web interfaces.
show_downloads: true
theme: jekyll-theme-minimal
